spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:3MB}
      max-request-size: ${MAX_REQUEST_SIZE:30MB}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/seletivoSeplagalexsandropereiragarcia002527}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:
  show-actuator: true

server:
  port: 8080

app:
  base-url: ${APP_BASE_URL:http://localhost:${server.port}}

regionais:
  url: ${REGIONAIS_URL:https://integrador-argus-api.geia.vip/v1/regionais}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:album-capas}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
security:
  jwt:
    secret: ${JWT_SECRET:change-me-use-256-bit-secret-key}
    access-token-expiration-minutes: ${JWT_ACCESS_EXP_MINUTES:5}
    refresh-token-expiration-days: ${JWT_REFRESH_EXP_DAYS:1}